version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: calculator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"
